language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"

script:
  - make update-source
  - make test

before_script: echo 'always_populate_raw_post_data = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini